# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-15 00:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_codec', models.CharField(max_length=20, verbose_name='audio codec')),
                ('audio_bitrate', models.PositiveIntegerField(default=0, verbose_name='audio bitrate')),
                ('audio_channels', models.PositiveIntegerField(blank=True, null=True, verbose_name='audio channels')),
                ('bitrate', models.PositiveIntegerField(verbose_name='average file bitrate')),
                ('duration', models.FloatField(verbose_name='duration')),
                ('size', models.PositiveIntegerField(verbose_name='size')),
                ('file', models.FileField(upload_to=b'avlogue/audio', verbose_name='file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudioFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_codec', models.CharField(max_length=20, verbose_name='audio codec')),
                ('audio_bitrate', models.PositiveIntegerField(default=0, verbose_name='audio bitrate')),
                ('audio_channels', models.PositiveIntegerField(blank=True, null=True, verbose_name='audio channels')),
                ('name', models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(message=b'Use only plain lowercase letters (ASCII), numbers and underscores.', regex=b'^[a-z0-9_-]+$')], verbose_name='name')),
                ('container', models.CharField(max_length=10, verbose_name='container format')),
                ('audio_codec_params', models.CharField(blank=True, max_length=400, verbose_name='audio codec params')),
            ],
            options={
                'verbose_name': 'audio format',
                'verbose_name_plural': 'audio formats',
            },
        ),
        migrations.CreateModel(
            name='AudioFormatSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message=b'Use only plain lowercase letters (ASCII), numbers and underscores.', regex=b'^[a-z0-9_-]+$')], verbose_name='name')),
                ('formats', models.ManyToManyField(to='avlogue.AudioFormat', verbose_name='formats')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudioStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(verbose_name='size')),
                ('file', models.FileField(upload_to=b'avlogue/audio/streams', verbose_name='stream file')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avlogue.AudioFormat')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='avlogue.AudioFile')),
            ],
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_codec', models.CharField(max_length=20, verbose_name='audio codec')),
                ('audio_bitrate', models.PositiveIntegerField(default=0, verbose_name='audio bitrate')),
                ('audio_channels', models.PositiveIntegerField(blank=True, null=True, verbose_name='audio channels')),
                ('video_codec', models.CharField(max_length=20, verbose_name='video codec')),
                ('video_bitrate', models.PositiveIntegerField(default=0, verbose_name='video bitrate')),
                ('video_width', models.IntegerField(blank=True, null=True, verbose_name='video width')),
                ('video_height', models.IntegerField(blank=True, null=True, verbose_name='video height')),
                ('bitrate', models.PositiveIntegerField(verbose_name='average file bitrate')),
                ('duration', models.FloatField(verbose_name='duration')),
                ('size', models.PositiveIntegerField(verbose_name='size')),
                ('file', models.FileField(upload_to=b'avlogue/video', verbose_name='file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_codec', models.CharField(max_length=20, verbose_name='audio codec')),
                ('audio_bitrate', models.PositiveIntegerField(default=0, verbose_name='audio bitrate')),
                ('audio_channels', models.PositiveIntegerField(blank=True, null=True, verbose_name='audio channels')),
                ('video_codec', models.CharField(max_length=20, verbose_name='video codec')),
                ('video_bitrate', models.PositiveIntegerField(default=0, verbose_name='video bitrate')),
                ('video_width', models.IntegerField(blank=True, null=True, verbose_name='video width')),
                ('video_height', models.IntegerField(blank=True, null=True, verbose_name='video height')),
                ('name', models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(message=b'Use only plain lowercase letters (ASCII), numbers and underscores.', regex=b'^[a-z0-9_-]+$')], verbose_name='name')),
                ('container', models.CharField(max_length=10, verbose_name='container format')),
                ('audio_codec_params', models.CharField(blank=True, max_length=400, verbose_name='audio codec params')),
                ('video_codec_params', models.CharField(blank=True, max_length=400, verbose_name='video codec params')),
                ('video_aspect_mode', models.CharField(choices=[(b'scale', 'scale'), (b'scale_crop', 'scale and crop')], default=b'scale', help_text='Aspect mode is only used if both video width and height sizes are specified,otherwise aspect mode will be ignored.', max_length=10, verbose_name='video aspect mode')),
            ],
            options={
                'verbose_name': 'video format',
                'verbose_name_plural': 'video formats',
            },
        ),
        migrations.CreateModel(
            name='VideoFormatSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message=b'Use only plain lowercase letters (ASCII), numbers and underscores.', regex=b'^[a-z0-9_-]+$')], verbose_name='name')),
                ('formats', models.ManyToManyField(to='avlogue.VideoFormat', verbose_name='formats')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(verbose_name='size')),
                ('file', models.FileField(upload_to=b'avlogue/video/streams', verbose_name='stream file')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avlogue.VideoFormat')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='avlogue.VideoFile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='videostream',
            unique_together=set([('media_file', 'format')]),
        ),
        migrations.AlterUniqueTogether(
            name='audiostream',
            unique_together=set([('media_file', 'format')]),
        ),
    ]
